<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TaskFlow.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TaskFlow.Application/TaskFlow.Application.csproj" />
    <ProjectReference Include="../TaskFlow.Domain/TaskFlow.Domain.csproj" />
  </ItemGroup>
</Project>
