<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TimewaysAPI.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TimewaysAPI.Domain/TimewaysAPI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>
</Project>
